djangoproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('htags/', include('htags.urls')),
    path('admin/', admin.site.urls),
    path('', include('htags.urls')),
]

htags/urls.py
from django.urls import path

from . import views

app_name = 'htags'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
]

htags/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone

class URL(models.Model):
    url_text = models.CharField(max_length=200)
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.url_text

    def was_created_recently(self):
        return self.create_at >= timezone.now() - datetime.timedelta(days=1)

htags/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from .models import URL
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import requests, bs4

def index(requests):
    if(requests.method == 'POST'):
        links = URL.objects.all()[:]
        if(extract(links)==True):
            message = 'Extracted sucessfully to sheet!'
            context = {
                'message': message
             }
            return render(requests, 'htags/index.html', context)
        else:
            message = 'error'
            context = {
                'message': message
            }
            return render(requests, 'htags/index.html', context)
    else:
        urls = URL.objects.all()[:]
        context = {
            'urls': urls
        }
        return render(requests, 'htags/index.html', context)

def add(request):
    if(request.method == 'POST'):
        url_text = []
        for i in range(55):
            poststr = 'hdrurl'+str(i+1)
            url_text.append(request.POST[poststr]) 
            try:
                URLValidator()(url_text[i])
            except ValidationError:
                return render(request, 'htags/add.html', {
                    'error_message': "Enter a valid URL for all fields",
                })
            url = URL(url_text=url_text[i])
            url.save()
        return redirect('/htags')
    else:
        items = list(range(55))
        context = {
            'items': items
        }
        return render(request, 'htags/add.html', context)


def extract(urllist):
    scope = ['https://spreadsheets.google.com/feeds',
        'https://www.googleapis.com/auth/drive']

    creds = ServiceAccountCredentials.from_json_keyfile_name('htags/client_secret.json', scope)
    client = gspread.authorize(creds)

    sheet = client.open('Bulk Meta Tag Extractor').sheet1

    hds = ['h1','h2','h3','h4','h5','h6']

    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'} 

    clearsheet(sheet)
    
    for i in range(len(urllist)):
        sheet.update_cell(i+2,1,str(urllist[i]))
    
    for i in range(len(urllist)): 
        result = urllist[i] 

        # read header of each url
        res = requests.get(result, headers=headers)
        res.raise_for_status()
        soup = bs4.BeautifulSoup(res.text, "html.parser")
        
        for j in range(6):
            helem = soup.select(hds[j])
            num = len(helem)
            cellupdate = ''
            for k in range(num):
                cellupdate += helem[k].getText() + '\n'
            newcell = cellupdate.strip()
            sheet.update_cell(i+2,j+2,newcell)
    return True 


def clearsheet(sheet):
    cell_list = sheet.range('A2:I'+ str(len(sheet.row_values(1))+2))

    for cell in cell_list:
        cell.value = ''
    
    sheet.update_cells(cell_list)    

htags/templates/htags/add.html
{% extends 'htags/layout.html' %}

{% block content %}
<h4 class='center-align'>Add URLs:</h4>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} 

<form action="{% url 'htags:add' %}" method="post">
    {% csrf_token %}
    {% for item in items %}   
    <input type="text" name="hdrurl{{ forloop.counter }}" id="hdrurl{{ forloop.counter }}" placeholder="URL {{ forloop.counter }}" value="" /><br/>
    <br>
    {% endfor %}
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
        <i class="material-icons right"></i>
    </button>
</form>
<br>
<br>
<a href="{% url 'htags:index' %}">Go Back</a>

{% endblock %}

htags/templates/htags/index.html
{% extends 'htags/layout.html' %}

{% block content %}

<h4>URL list</h4>

<form class="col s12" action="{% url 'htags:index' %}" method="post">
    {% csrf_token %}
    {% for url in urls %} 
    <div class="row">
        <div class="input-field col s12">
            <input readonly="readonly" value="{{url.url_text}}" id="disabled" type="text" class="validate">
        </div>
    </div>
    {% endfor %}
    <br>
    <button class="btn waves-effect waves-light" type="submit" name="action">Extract
        <i class="material-icons right"></i>
    </button>
    <br>
</form>
<br>

<div id="wait" style="display:none">
    <br>Extracting...
</div>

<script>
    $(document).ready(function(){
        
        $("btn waves-effect waves-light").click(function(){
            $("#wait").show();
        });
    });
</script>

{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}

{% endblock %}

htags/templates/htags/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <title>Header Meta Tag Extractor</title>
</head>
<body>
    <header>
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Header Meta Tag Extractor</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a class="" href="{% url 'htags:index' %}">List</a></li>
                    <li><a class="" href="{% url 'htags:add' %}">Add</a></li>
                    <li><a target="_blank" href="https://docs.google.com/spreadsheets/d/1VJzHOjDrSrLE3lKb7DD9cbabqFnlWzf_iCYsbvCg1QA/edit#gid=0">Open Sheet</a></li>
                    <li><a class="" href="/admin">Admin</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>   
</body>
</html>